# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170924_0738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('share_post', 'Share Post'), ('comment_on_post', 'Comment on Post'))},
        ),
    ]
