# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-24 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20170924_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
